disabled_rules:
- redundant_optional_initialization
- trailing_whitespace
- force_try
- identifier_name

line_length:
  warning: 200
  error: 250
  ignores_comments: true
  ignores_function_declarations: true

excluded:
- Pods
